#!/bin/python2
#coding=utf-8
import os,sys,time
def maung(n):
    for m in n + '\n':
        sys.stdout.write(m)
        sys.stdout.flush()
        time.sleep(0.001)
banner = """
[0m[1;32m                    uuuuuuu
                uu$$$$$$$$$$$uu
             uu$$$$$$$$$$$$$$$$$uu
            u$$$$$$$$$$$$$$$$$$$$$u
           u$$$$$$$$$$$$$$$$$$$$$$$u
          u$$$$$$$$$$$$$$$$$$$$$$$$$u
          u$$$$$$$$$$$$$$$$$$$$$$$$$u
          u$$$$$$x   x$$$x   x$$$$$$u
          x$$$$x      u$u       $$$$x
           $$$u       u$u       u$$$
           $$$u      u$$$u      u$$$
            x$$$$uu$$$   $$$uu$$$$x
             x$$$$$$$x   x$$$$$$$x
               u$$$$$$$u$$$$$$$u
                u$x$x$x$x$x$x$u
     uuu        $$u$ $ $ $ $u$$       uuu
    u$$$$        $$$$$u$u$u$$$       u$$$$
     $$$$$uu      x$$$$$$$$$x     uu$$$$$$
   u$$$$$$$$$$$uu    xxxxx    uuuu$$$$$$$$$$
   $$$$xxx$$$$$$$$$$uuu   uu$$$$$$$$$xxx$$$x
    xxx      xx$$$$$$$$$$$uu xx$xxx
              uuuu xx$$$$$$$$$$uuu
     u$$$uuu$$$$$$$$$uu xx$$$$$$$$$$$uuu$$$
     $$$$$$$$$$xxxx           xx$$$$$$$$$$$x
      x$$$$$x                      xx$$$$xx
        $$$x                         $$$$x [0m"""

os.system("clear")
maung(banner)
print
